### ISSUE TITLE
Fix "ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'" after upgrading to Flask/Werkzeug 2.10

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#119]
Got an import error after upgrading to Flask/Werkzeug 2.10:
`
Traceback (most recent call last):
  File "/home/brettk/.pyenv/versions/3.10.3/envs/contextualise-dev-2/lib/python3.10/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/home/brettk/Source/structured-knowledge/contextualise/contextualise/__init__.py", line 14, in <module>
    from flask_seasurf import SeaSurf
  File "/home/brettk/.pyenv/versions/3.10.3/envs/contextualise-dev-2/lib/python3.10/site-packages/flask_seasurf.py", line 30, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/home/brettk/.pyenv/versions/3.10.3/envs/contextualise-dev-2/lib/python3.10/site-packages/werkzeug/security.py)
`

**Comment by brettkromkamp** [comment]
Initial testing confirms that this was fixed with: https://github.com/maxcountryman/flask-seasurf/pull/108. Once definitively confirmed that this has been fixed, this issue will be closed.

**Comment by brettkromkamp** [comment]
Confirmed to be fixed with latest Flask-SeaSurf update.
