### ISSUE TITLE
OSX installation

### ISSUE THREAD

**Issue by tonyday567** [brettkromkamp/contextualise#42]
I have attempted to install on my mac from scratch with the following steps:

```
brew install python
brew install postgresql
git clone https://github.com/brettkromkamp/topic-db.git
cd topic-db
pip install -e .
cd ../
git clone https://github.com/brettkromkamp/contextualise
cd contextualise
pip install -e .
cd ../
```

All good!

Then created a directory for the 'project' ie somewhere to place a settings.ini (and a topicmap-definition.sql):

```
mkdir first
cd first
```

Then edited settings.ini to:

```
[DATABASE]
Username = testuser
Password = password
Database = testname
Host = localhost
Port = 5432
```

Then create a test database.

```
psql postgres
CREATE USER testuser WITH PASSWORD 'password';
CREATE DATABASE testname OWNER testuser;
\q
psql -h localhost -U testuser -d testname -a -f topicmap-definition.sql
```

All looked good!

Then run flask:

```
export FLASK_APP=contextualise
export FLASK_ENV=development
flask run
```

And it looked like the readme example.

But then, when I open http://127.0.0.1:5000/ I get a KeyError, specifically for `database_username = config["DATABASE"]["Username"]`.

I have never used postgres before, but am guessing I may need to log on as that user?

Any help appreciated, I feel close to a successful install!

**Comment by brettkromkamp** [comment]
@tonyday567 Can you confirm that you are installing Python 3 with `brew install python` (just run `python --version` in the terminal). I personally don't have a Mac, but I do know that installing on Mac is proving to be somewhat challenging. By the way, it is my intention to make Contextualise publicly available (hopefully within the next week).

**Comment by brettkromkamp** [comment]
@tonyday567 Could you provide the full stack trace?

**Comment by tonyday567** [comment]
Installing postgres first gave me all the build prerequisites mentioned in the readme, so it was fairly painless. The main bug I ran into was installing postgres splatted python somehow, by mixing up openssl. And then a `brew reinstall python` fixed that. 

Versions and stack trace below:

```
# which python
/usr/local/opt/python/libexec/bin/python

# which pip
/usr/local/opt/python/libexec/bin/pip

# python --version
Python 3.7.1

# pip --version
pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

# brew info python
python: stable 3.7.6 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/3.7.0 (10,088 files, 185.6MB)
  Built from source on 2018-07-31 at 08:10:47
/usr/local/Cellar/python/3.7.1 (3,973 files, 61.8MB) *
  Poured from bottle on 2018-12-15 at 15:13:13
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✘, xz ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 447,477 (30 days), 1,436,982 (90 days), 5,655,491 (365 days)
install-on-request: 235,131 (30 days), 726,619 (90 days), 2,827,067 (365 days)
build-error: 0 (30 days)

# brew unlink openssl
Unlinking /usr/local/Cellar/openssl@1.1/1.1.1d... 0 symlinks removed

# postgres -V
postgres (PostgreSQL) 12.1
```

stack trace:

```
127.0.0.1 - - [14/Feb/2020 10:24:59] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tonyday/context/contextualise/contextualise/__init__.py", line 17, in <module>
    from contextualise.security import user_store, user_models
  File "/Users/tonyday/context/contextualise/contextualise/security/user_store.py", line 20, in <module>
    database_username = config["DATABASE"]["Username"]
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'DATABASE'
127.0.0.1 - - [14/Feb/2020 10:24:59] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
```
