### ISSUE TITLE
Failed to open the home page due to an error in running Flask

### ISSUE THREAD

**Issue by zhuliangbing** [brettkromkamp/contextualise#43]
flask.cli.NoAppException
flask.cli.NoAppException: While importing "contextualise", an ImportError was raised:

Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\contextualise\contextualise\__init__.py", line 13, in <module>
    from flask_mail import Mail
ModuleNotFoundError: No module named 'flask_mail'

Traceback (most recent call last)
File "D:\contextualise\contextualise\__init__.py", line 13, in <module>
from flask_mail import Mail
During handling of the above exception, another exception occurred:
File "D:\python\Lib\site-packages\flask\cli.py", line 343, in __call__
rv = self._load_unlocked()
File "D:\python\Lib\site-packages\flask\cli.py", line 330, in _load_unlocked
self._app = rv = self.loader()
File "D:\python\Lib\site-packages\flask\cli.py", line 388, in load_app
app = locate_app(self, import_name, name)
File "D:\python\Lib\site-packages\flask\cli.py", line 245, in locate_app
raise NoAppException(
flask.cli.NoAppException: While importing "contextualise", an ImportError was raised:

Traceback (most recent call last):
File "d:\python\lib\site-packages\flask\cli.py", line 240, in locate_app
__import__(module_name)
File "D:\contextualise\contextualise\__init__.py", line 13, in <module>
from flask_mail import Mail
ModuleNotFoundError: No module named 'flask_mail'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by brettkromkamp** [comment]
Fixed many moons ago!
